In [4]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB,BernoulliNB,GaussianNB
import numpy as np

In [4]:
text_data = np.array(['I love Brazil. Brazil!',
                      'Brazil is best',
                      'Germany beats both'])

text_data

array(['I love Brazil. Brazil!', 'Brazil is best', 'Germany beats both'],
      dtype='<U22')

In [8]:
# Create bag of words
count = CountVectorizer()
bag_of_words = count.fit_transform(text_data)

# Create feature matrix
X = bag_of_words.toarray()
X

array([[0, 0, 0, 2, 0, 0, 1],
       [0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 0]], dtype=int64)

In [5]:
y = np.array([0,0,1])
y

array([0, 0, 1])

In [9]:
# Create multinomial naive Bayes object with prior probabilities of each class
clf = MultinomialNB(class_prior=[0.25, 0.5])

# Train model
model = clf.fit(X, y)

In [10]:
# Create new observation
new_observation = [[0, 0, 0, 1, 0, 1, 0]]

In [11]:
# Predict new observation's class
model.predict(new_observation)

array([0])

# --------------------------------------------------------------------------------------

In [6]:
import pandas as pd
import numpy as np
#import matplotlib.pyplot as plt
import seaborn as sns
import pandas_profiling 
# __________________________________________________

from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn.model_selection import GridSearchCV,train_test_split
from sklearn.naive_bayes import BernoulliNB

# Loading Datasets 

### Load_dataset using sklearn

In [13]:
from sklearn.datasets import load_boston

data = load_boston()

In [15]:
data.__class__ # This is object type
                # data is basically a dictionary object 

sklearn.utils.Bunch

In [16]:
data.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [35]:
#print(data.DESCR) # Gives you a formatted description about the data object

In [17]:
boston =  pd.DataFrame(data=data['data'],columns=data['feature_names'])

In [18]:
boston.head(2)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   

   PTRATIO      B  LSTAT  
0     15.3  396.9   4.98  
1     17.8  396.9   9.14

In [19]:
boston.shape

(506, 13)

### Load_dataset using seaborn

In [20]:
sns.get_dataset_names()

/home/rohan/anaconda3/lib/python3.6/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 193 of the file /home/rohan/anaconda3/lib/python3.6/runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))


['anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'iris',
 'mpg',
 'planets',
 'tips',
 'titanic']

# ------------------------------------------------------------------------------------

# Naive_Bayes

In [7]:
titanic  = sns.load_dataset('titanic')

In [22]:
titanic.head(2)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False

In [23]:
titanic.describe().T

count       mean        std   min      25%      50%   75%       max
survived  891.0   0.383838   0.486592  0.00   0.0000   0.0000   1.0    1.0000
pclass    891.0   2.308642   0.836071  1.00   2.0000   3.0000   3.0    3.0000
age       714.0  29.699118  14.526497  0.42  20.1250  28.0000  38.0   80.0000
sibsp     891.0   0.523008   1.102743  0.00   0.0000   0.0000   1.0    8.0000
parch     891.0   0.381594   0.806057  0.00   0.0000   0.0000   0.0    6.0000
fare      891.0  32.204208  49.693429  0.00   7.9104  14.4542  31.0  512.3292

- Simple binnig based on quartile distribution
- This ignores the distribution of Y's for the binning

In [24]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

#### Using Qcut for quantiles based cutting data/Bucketing continuos data

- Used for Deciling with labels = False, this gives the Decile number instead of tags(as we have used here)

- Alternative Method - Using Apply(filter-UDF) 
- We can also use np.where(condition, True,false)

In [14]:
# titanic['fare_cat'] = titanic.fare.apply(filter_)
# titanic.head()

# def filter_(x):
#     if x>40:
#         return 'High'
#     if x>28 and x<40:
#         return 'Medium'
#     if x < 28 and x>20:
#         return 'Low'
#     if x < 20:
#         return 'very_low'
#     else:
#         'kaise'

#### Encoding `Fare` & `Age`

In [8]:
titanic['fare_cat']  = pd.qcut(titanic.fare,4,labels=['very_Low','low','medium','High'])


titanic['Age_cat']  = pd.cut(titanic.age,[1,14,20,40,80],labels=['child','teen','Adult','Old'])    

In [26]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  fare_cat Age_cat  
0    man        True  NaN  Southampton    no  False  very_Low   Adult  
1  woman       False    C    Cherbourg   yes  False      High   Adult  
2  woman       False  NaN  Southampton   yes   True       low   Adult  
3  woman       False    C  Southampton   yes  False      High   Adult  
4    man        True  NaN  Southampton    no   True       low   Adult

#### Dropping Fare & age - 

In [9]:
titanic.drop(columns=['fare','age'],inplace=True)
titanic.head(2)

survived  pclass     sex  sibsp  parch embarked  class    who  adult_male  \
0         0       3    male      1      0        S  Third    man        True   
1         1       1  female      1      0        C  First  woman       False   

  deck  embark_town alive  alone  fare_cat Age_cat  
0  NaN  Southampton    no  False  very_Low   Adult  
1    C    Cherbourg   yes  False      High   Adult

- Since we now have all columns as categorical, Next we would be encoding them 

- Checking for `NA` values in  between

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

#### Handling NA values

In [29]:
titanic.head(2)

survived  pclass     sex  sibsp  parch embarked  class    who  adult_male  \
0         0       3    male      1      0        S  Third    man        True   
1         1       1  female      1      0        C  First  woman       False   

  deck  embark_town alive  alone  fare_cat Age_cat  
0  NaN  Southampton    no  False  very_Low   Adult  
1    C    Cherbourg   yes  False      High   Adult

In [30]:
titanic.isnull().sum().to_frame().T

# only columns with null values are 

# embarked & embarked_town - will remove 2 obs 
# deck - will remove the column(doesnot seen important as well)
# fare_cat -  will fill it using backfill method

survived  pclass  sex  sibsp  parch  embarked  class  who  adult_male  \
0         0       0    0      0      0         2      0    0           0   

   deck  embark_town  alive  alone  fare_cat  Age_cat  
0   688            2      0      0         0      191

- step_1 :  Removing 'deck' columns - contains 680 NA values

In [11]:
# Removing 'deck' columns - contains 680 NA values
titanic.drop(columns='deck',inplace=True)

- Step_2 - # filling NA using backfill 

In [12]:
# filling NA using backfill 

# Age category
titanic.Age_cat.fillna(method= 'ffill',inplace=True)

- Step_3 - Removing the 2 obs for which `embark` & `embark_town` are null

In [13]:
# Removing the 2 obs for which `embark` & `embark_town` are null

titanic.dropna(axis = 0,inplace=True)

In [34]:
titanic.isnull().sum().to_frame().T # no null values

survived  pclass  sex  sibsp  parch  embarked  class  who  adult_male  \
0         0       0    0      0      0         0      0    0           0   

   embark_town  alive  alone  fare_cat  Age_cat  
0            0      0      0         0        0

In [36]:
titanic.head(2)

survived  pclass     sex  sibsp  parch embarked  class    who  adult_male  \
0         0       3    male      1      0        S  Third    man        True   
1         1       1  female      1      0        C  First  woman       False   

   embark_town alive  alone  fare_cat Age_cat  
0  Southampton    no  False  very_Low   Adult  
1    Cherbourg   yes  False      High   Adult

### Encoding Categorical Variable

- Checking for categorical var

In [14]:
cat_cols   =  titanic.columns.difference(['parch','survived','pclass','sibsp'])

cat_cols

Index(['Age_cat', 'adult_male', 'alive', 'alone', 'class', 'embark_town',
       'embarked', 'fare_cat', 'sex', 'who'],
      dtype='object')

In [15]:
## Encoding multiple columns ast once

titanic[cat_cols] = titanic[cat_cols].apply(lambda x:le.fit_transform(x))

#### Final dataset

In [40]:
titanic.head(2)

survived  pclass  sex  sibsp  parch  embarked  class  who  adult_male  \
0         0       3    1      1      0         2      2    1           1   
1         1       1    0      1      0         0      0    2           0   

   embark_town  alive  alone  fare_cat  Age_cat  
0            2      0      0         3        0  
1            0      1      0         0        0

In [16]:
titanic.survived.value_counts()

0    549
1    340
Name: survived, dtype: int64

#### Spilitting data

In [18]:
x = titanic[titanic.columns.difference(['survivied'])]
y = titanic.survived

In [19]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=0)

print('x_train:',X_train.shape)
print('x_test:',X_test.shape)
print('y_train:',y_train.shape)
print('y_test:',y_test.shape)

x_train: (533, 14)
x_test: (356, 14)
y_train: (533,)
y_test: (356,)


In [20]:
y_train.value_counts(),y_test.value_counts()

(0    333
 1    200
 Name: survived, dtype: int64, 0    216
 1    140
 Name: survived, dtype: int64)

- The model is a clear case of overfitting.
- This is because of too much of encoding of categorical variables

### Fitting using bagging classifier 

In [21]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
bag_class =  BaggingClassifier(base_estimator= DecisionTreeClassifier(),n_estimators=50)

In [22]:
bag_class.fit(X_train,y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=50, n_jobs=None, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [23]:
bag_pred = bag_class.predict(X_test)

In [24]:
metrics.accuracy_score(y_test,bag_pred)

1.0

### Fitting using bernoulli NB`

- As we can see NB does not give a lot of params to play with :
    
    - `alpha` : float, optional (default=1.0)
    Additive (Laplace/Lidstone) smoothing parameter
    (0 for no smoothing).
    
    - `fit_prior` : boolean, optional (default=True)
    Whether to learn class prior probabilities or not.
    If false, a uniform prior will be used.
    
    - `class_prior` : array-like, size=[n_classes,], optional (default=None)
    Prior probabilities of the classes. If specified the priors are not
    adjusted according to the data

In [26]:
ber_NB =  BernoulliNB()
ber_NB.fit(X_train,y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [27]:
NB_pred = ber_NB.predict(X_test)

In [51]:
metrics.confusion_matrix(y_test,NB_pred)

array([[216,   0],
       [  0, 140]])

In [52]:
metrics.roc_auc_score(y_test,NB_pred)

1.0

#### Other Imp Metrics

In [61]:
ber_NB.class_count_ ### counts of classes 1/0

array([333., 200.])

In [64]:
ber_NB.class_log_prior_ ### log(y=1/y=total) & log(y=0/y=total)

array([-0.47037893, -0.98020406])

In [81]:
ber_NB.feature_log_prob_    #### Empirical log probability of features given a class, P(x_i|y)

array([[-7.08185058e-01, -1.86509418e-01, -5.81413053e+00,
        -3.54545018e-01, -1.65156294e-01, -1.61641352e-01,
        -1.61641352e-01, -2.04658737e-01, -1.71978597e+00,
        -2.98953885e-03, -1.47703844e-01, -1.32549416e+00,
        -5.81413053e+00, -6.79273413e-02],
       [-7.03097511e-01, -1.43706669e+00, -4.96278934e-03,
        -7.64972915e-01, -4.79953960e-01, -3.45423067e-01,
        -3.45423067e-01, -4.40733247e-01, -1.14938461e+00,
        -4.96278934e-03, -1.18113331e+00, -9.01548450e-01,
        -4.96278934e-03, -1.78368982e-01]])

In [82]:
ber_NB.feature_count_  ####  Number of samples encountered for each (class, feature)
                        #### during fitting. This value is weighted by the sample weight when
                        #### provided.

array([[164., 277.,   0., 234., 283., 284., 284., 272.,  59., 333., 288.,
         88.,   0., 312.],
       [ 99.,  47., 200.,  93., 124., 142., 142., 129.,  63., 200.,  61.,
         81., 200., 168.]])